### ISSUE TITLE
Error: Debug adapter doesn't support 'swim' transport

### ISSUE THREAD

**Issue by MarrekNozka** [hbendalibraham/stm8_started#1]
I begin with stm8 (I have nucleo STM8S208RB).  I use your HowTo. Thank you very much. 

But I have problem with openocd. I compiled openocd from git repository.

I run:
```
openocd -f interface/stlink.cfg -f target/stm8s105.cfg -c "init" -c "reset halt"
```

I get this:
```
Open On-Chip Debugger 0.10.0+dev-01267-g4c364b45-dirty (2020-06-05-08:14)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Error: Debug adapter doesn't support 'swim' transport
/usr/local/stow/openocd/bin/../share/openocd/scripts/target/stm8s.cfg:7: Error: 
in procedure 'script' 
at file "embedded:startup.tcl", line 26
at file "/usr/local/stow/openocd/bin/../share/openocd/scripts/target/stm8s105.cfg", line 8
at file "/usr/local/stow/openocd/bin/../share/openocd/scripts/target/stm8s.cfg", line 7
```

Where am I making mistake? Thanks!

**Comment by MarrekNozka** [comment]
I installed [xPack OpenOCD binaries](https://xpack.github.io/openocd/install/#manual-install) and it works.

**Comment by spth** [comment]
Looks like the OpenOCD you used on your first attempt was too old.

**Comment by ali-libre** [comment]
i'm using arch too.
but i got same error

**Comment by trajamohan** [comment]
The transport SWIM has been moved away from HLA and is now in 'interface/stlink-dap.cfg'

Use : openocd -f interface/stlink-dap.cfg -f target/stm8s105.cfg -c "init" -c "reset halt"

**Comment by MarrekNozka** [comment]
Thank you very much. It's works with latest version of openocd.
