### ISSUE TITLE
SDCC version in introduction

### ISSUE THREAD

**Issue by spth** [hbendalibraham/stm8_started#2]
The introduction mentions "SDCC Compiler v3.5.0 or higher." But for the on-target debugging SDCC 3.5.0 won't work well; it needs the DWARFv2 improvements that are in SDCC 3.7.0 (see also https://sourceforge.net/p/sdcc/wiki/SDCC%203.7.0%20Release/).

So I'd recommend to change the introduction to require SDCC 3.7.0 or later.

**Comment by hbend1li** [comment]
thank you for your contribution, version are fixed in 2b609d2fff2022ebf7ffa0e23df0a0a1997515c4
